module.exports = {
    //WL_PROPOSAL: 'wla',
    //AA_PROPOSAL: 'aaa',
    //AU_PROPOSAL: 'aua',
    //ML_PROPOSAL: 'mla',
    //DCV_PERMIT_PROPOSAL: 'dcvp',
    //DCV_ADMISSION_PROPOSAL: 'dcv',

    //WL_APPROVAL: 'wla',
    //AA_APPROVAL: 'aap',
    //AU_APPROVAL: 'aup',
    //ML_APPROVAL: 'ml',
	APPLICATION_TYPE: {
		REGISTRATION_OF_INTEREST: 'registration_of_interest',
		LEASE: 'lease',
		LICENCE: 'licence',
	},
	DRAFT: 'Draft',
	WITH_ASSESSOR: 'With Assessor',
	WITH_ASSESSOR_CONDITIONS: 'With Assessor (Conditions)',
	WITH_APPROVER: 'With Approver',
	WITH_REFERRAL: 'With Referral',
	WITH_REFERRAL_CONDITIONS: 'With Referral (Conditions)',
	APPROVED_APPLICATION: 'Approved (Application)',
	APPROVED_COMPETITIVE_PROCESS: 'Approved (Competitive Process)',
	APPROVED_EDITING_INVOICING: 'Approved (Editing Invoicing)',
	APPROVED: 'Approved',
	DECLINED: 'Declined',
	DISCARDED: 'Discarded',
};
