# Generated by Django 3.2.4 on 2021-12-17 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaseslicensing", "0003_auto_20211217_1019"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposal",
            name="assessor_data",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="comment_data",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="data",
        ),
        migrations.RemoveField(
            model_name="proposal",
            name="schema",
        ),
    ]
