# Generated by Django 3.2.4 on 2021-12-23 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leaseslicensing", "0007_deedpolldocument"),
    ]

    operations = [
        migrations.CreateModel(
            name="MapLayer",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("layer_name", models.CharField(blank=True, max_length=200, null=True)),
                ("option_for_internal", models.BooleanField(default=True)),
                ("option_for_external", models.BooleanField(default=True)),
                ("display_all_columns", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "map layer",
            },
        ),
        migrations.CreateModel(
            name="MapColumn",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("option_for_internal", models.BooleanField(default=True)),
                ("option_for_external", models.BooleanField(default=True)),
                (
                    "map_layer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="leaseslicensing.maplayer",
                    ),
                ),
            ],
            options={
                "verbose_name": "map column",
            },
        ),
    ]
