# Generated by Django 3.2.4 on 2022-01-14 03:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("leaseslicensing", "0008_mapcolumn_maplayer"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProposalGeometry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "polygons",
                    django.contrib.gis.db.models.fields.MultiPolygonField(
                        blank=True, null=True, srid=4326
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="leaseslicensing.proposal",
                    ),
                ),
            ],
        ),
    ]
