# Generated by Django 3.2.4 on 2022-01-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0009_proposalgeometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposalgeometry',
            name='intersects',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
