# Generated by Django 3.2.4 on 2022-01-19 07:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0010_proposalgeometry_intersects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalgeometry',
            name='intersects',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='proposalgeometry',
            name='polygons',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='proposalgeometry',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaseslicensing.proposal'),
        ),
    ]
