# Generated by Django 3.2.4 on 2022-01-19 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0012_rename_polygons_proposalgeometry_polygon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalgeometry',
            name='proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposalgeometry', to='leaseslicensing.proposal'),
        ),
    ]
