# Generated by Django 3.2.4 on 2022-01-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaseslicensing", "0014_remove_proposal_customer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="ind_applicant",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("with_assessor", "With Assessor"),
                    ("with_assessor_conditions", "With Assessor (Conditions)"),
                    ("with_approver", "With Approver"),
                    ("with_referral", "With Referral"),
                    ("with_referral_conditions", "With Referral (Conditions)"),
                    ("approved_application", "Approved (Application)"),
                    ("approved_competitive_process", "Approved (Competitive Process)"),
                    ("approved_editing_invoicing", "Approved (Editing Invoicing)"),
                    ("approved", "Approved"),
                    ("declined", "Declined"),
                    ("discarded", "Discarded"),
                ],
                default="with_assessor",
                max_length=30,
                verbose_name="Processing Status",
            ),
        ),
    ]
