# Generated by Django 3.2.4 on 2022-02-03 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0023_auto_20220202_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationtype',
            name='name',
            field=models.CharField(choices=[('registration_of_interest', 'Registration of Interest'), ('lease_licence', 'Lease Licence')], max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='oraclecode',
            name='code_type',
            field=models.CharField(choices=[('registration_of_interest', 'registration_of_interest'), ('lease_licence', 'lease_licence')], default='registration_of_interest', max_length=64, verbose_name='Application Type'),
        ),
        migrations.CreateModel(
            name='ChecklistQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('map', 'Map'), ('proposal_details', 'Proposal Details'), ('proposal_impact', 'Proposal Impact'), ('other', 'Other'), ('deed_poll', 'Deed Poll'), ('related_items', 'Related Items')], default='map', max_length=50, verbose_name='Section')),
                ('list_type', models.CharField(choices=[('assessor_list', 'Assessor Checklist'), ('referral_list', 'Referral Checklist')], default='assessor_list', max_length=30, verbose_name='Checklist type')),
                ('enabled', models.BooleanField(default=True)),
                ('application_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.applicationtype')),
            ],
        ),
    ]
