# Generated by Django 3.2.4 on 2022-02-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaseslicensing", "0025_auto_20220203_1303"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proposalassessment",
            name="referral_assessment",
        ),
    ]
