# Generated by Django 3.2.4 on 2022-02-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaseslicensing", "0026_remove_proposalassessment_referral_assessment"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ChecklistQuestions",
            new_name="SectionChecklistQuestions",
        ),
    ]
