# Generated by Django 3.2.4 on 2022-02-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaseslicensing", "0027_rename_checklistquestions_sectionchecklistquestions"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="checklistquestion",
            options={"ordering": ["order"]},
        ),
        migrations.AlterModelOptions(
            name="sectionchecklistquestions",
            options={
                "verbose_name": "Section Questions",
                "verbose_name_plural": "Section Questions",
            },
        ),
    ]
