# Generated by Django 3.2.4 on 2022-02-07 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0030_auto_20220207_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalassessment',
            name='submitter',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
