# Generated by Django 3.2.4 on 2022-02-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0030_availableactivitiesdocument_capitalinvestmentdocument_cashflowdocument_financialcapacitydocument_key'),
        ('leaseslicensing', '0033_auto_20220207_1529'),
    ]

    operations = [
    ]
