# Generated by Django 3.2.4 on 2022-02-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0035_checklistquestion_shown_to_others'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistquestion',
            name='shown_to_others',
            field=models.BooleanField(default=False, help_text='When checked, question is shown to others', verbose_name='Comment'),
        ),
    ]
