# Generated by Django 3.2.12 on 2022-02-23 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leaseslicensing", "0038_auto_20220223_0953"),
    ]

    operations = [
        migrations.AddField(
            model_name="proposal",
            name="shapefile_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
