# Generated by Django 3.2.12 on 2022-02-24 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0040_additionaldocumenttype'),
        ('leaseslicensing', '0040_alter_approval_proxy_applicant'),
    ]

    operations = [
    ]
