# Generated by Django 3.2.12 on 2022-02-25 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0041_merge_20220224_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='maplayer',
            name='transparency',
            field=models.PositiveSmallIntegerField(default=50),
        ),
    ]
