# Generated by Django 3.2.12 on 2022-03-03 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0042_maplayer_transparency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proposalrequirement',
            options={'ordering': ['proposal', 'req_order']},
        ),
        migrations.RemoveField(
            model_name='proposalrequirement',
            name='order',
        ),
        migrations.AddField(
            model_name='proposalrequirement',
            name='req_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='proposalrequirement',
            constraint=models.UniqueConstraint(fields=('proposal', 'req_order'), name='unique requirement order per proposal'),
        ),
    ]
