# Generated by Django 3.2.12 on 2022-03-11 07:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0043_auto_20220303_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='generated_lease_licence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_of_interest', to='leaseslicensing.proposal'),
        ),
    ]
