# Generated by Django 3.2.12 on 2022-04-11 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("leaseslicensing", "0043_additionaldocument_proposaladditionaldocumenttype"),
        ("leaseslicensing", "0046_auto_20220311_1609"),
    ]

    operations = []
