# Generated by Django 3.2.13 on 2022-07-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0047_merge_20220411_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('details_placeholder', models.CharField(max_length=200)),
            ],
        ),
    ]
