# Generated by Django 3.2.13 on 2022-08-03 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0047_merge_20220411_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveProcess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='competitive_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.competitiveprocess'),
        ),
    ]
