# Generated by Django 3.2.13 on 2022-08-03 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0048_auto_20220803_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='competitive_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposals', to='leaseslicensing.competitiveprocess'),
        ),
    ]
