# Generated by Django 3.2.13 on 2022-07-27 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0049_auto_20220727_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltype',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
