# Generated by Django 3.2.13 on 2022-08-05 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0050_competitiveprocess_lodgement_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competitiveprocess',
            options={'verbose_name': 'Competitive Process', 'verbose_name_plural': 'Competitive Processes'},
        ),
        migrations.AddField(
            model_name='competitiveprocess',
            name='status',
            field=models.CharField(choices=[('in_progress', 'In Progress'), ('discarded', 'Discarded'), ('completed_application', 'Completed (Application)'), ('completed_declined', 'Completed (Declined)')], default='in_progress', max_length=30, verbose_name='Status'),
        ),
    ]
