# Generated by Django 3.2.13 on 2022-07-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0050_alter_approvaltype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltype',
            name='details_placeholder',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
