# Generated by Django 3.2.13 on 2022-08-04 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0048_auto_20220803_0904'),
        ('leaseslicensing', '0052_proposedapprovaldocument'),
    ]

    operations = [
    ]
