# Generated by Django 3.2.13 on 2022-08-08 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0052_alter_proposal_competitive_process'),
        ('leaseslicensing', '0053_merge_20220804_1652'),
    ]

    operations = [
    ]
