# Generated by Django 3.2.13 on 2022-08-05 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0050_competitiveprocess_lodgement_number'),
        ('leaseslicensing', '0053_merge_20220804_1652'),
    ]

    operations = [
    ]
