# Generated by Django 3.2.13 on 2022-08-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0054_merge_20220808_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveprocess',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='competitiveprocess',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
