# Generated by Django 3.2.13 on 2022-08-09 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0055_auto_20220809_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveprocess',
            name='assigned_officer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
