# Generated by Django 3.2.13 on 2022-08-09 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0056_competitiveprocess_assigned_officer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitiveprocess',
            old_name='assigned_officer',
            new_name='assigned_officer_id',
        ),
    ]
