# Generated by Django 3.2.13 on 2022-08-10 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0054_merge_20220805_1144'),
        ('leaseslicensing', '0057_rename_assigned_officer_competitiveprocess_assigned_officer_id'),
    ]

    operations = [
    ]
