# Generated by Django 3.2.13 on 2022-08-12 03:22

from django.db import migrations, models
import django.db.models.deletion
import leaseslicensing.components.proposals.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0059_approvalsubtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseLicenceApprovalDocumentCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lease_licence_approval_document_collection', to='leaseslicensing.proposal')),
            ],
        ),
        migrations.CreateModel(
            name='LeaseLicenceApprovalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, upload_to=leaseslicensing.components.proposals.models.update_proposal_doc_filename)),
                ('input_name', models.CharField(blank=True, max_length=255, null=True)),
                ('can_delete', models.BooleanField(default=True)),
                ('can_hide', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('document_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leaseslicensing.leaselicenceapprovaldocumentcollection')),
            ],
            options={
                'verbose_name': 'Proposed Approval Document',
            },
        ),
    ]
