# Generated by Django 3.2.13 on 2022-08-12 04:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0061_auto_20220812_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalTypeDocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('approval_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_type_document_types', to='leaseslicensing.approvaltype')),
            ],
        ),
        migrations.RemoveField(
            model_name='leaselicenceapprovaldocument',
            name='document_collection',
        ),
        migrations.AddField(
            model_name='leaselicenceapprovaldocument',
            name='approval_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lease_licence_approval_documents', to='leaseslicensing.approvaltype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leaselicenceapprovaldocument',
            name='proposal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lease_licence_approval_documents', to='leaseslicensing.proposal'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='LeaseLicenceApprovalDocumentCollection',
        ),
        migrations.AddField(
            model_name='leaselicenceapprovaldocument',
            name='approval_type_document_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='lease_licence_approval_documents', to='leaseslicensing.approvaltypedocumenttype'),
            preserve_default=False,
        ),
    ]
