# Generated by Django 3.2.13 on 2022-08-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0062_auto_20220812_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvaltypedocumenttype',
            name='approval_type',
        ),
        migrations.AddField(
            model_name='approvaltypedocumenttype',
            name='approval_type',
            field=models.ManyToManyField(to='leaseslicensing.ApprovalType'),
        ),
    ]
