# Generated by Django 3.2.13 on 2022-08-12 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0064_auto_20220812_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaltype',
            name='approval_type_document_types',
            field=models.ManyToManyField(to='leaseslicensing.ApprovalTypeDocumentType'),
        ),
    ]
