# Generated by Django 3.2.13 on 2022-08-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0059_competitiveprocessgeometry'),
        ('leaseslicensing', '0065_alter_approvaltype_approval_type_document_types'),
    ]

    operations = [
    ]
