# Generated by Django 3.2.13 on 2022-08-16 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0066_merge_20220812_1715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalrequireddocument',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='proposalrequireddocument',
            name='required_doc',
        ),
        migrations.RemoveField(
            model_name='qaofficerdocument',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='qaofficerreferral',
            name='document',
        ),
        migrations.RemoveField(
            model_name='qaofficerreferral',
            name='proposal',
        ),
        migrations.RemoveField(
            model_name='qaofficerreferral',
            name='qaofficer_group',
        ),
        migrations.DeleteModel(
            name='OnHoldDocument',
        ),
        migrations.DeleteModel(
            name='ProposalRequiredDocument',
        ),
        migrations.DeleteModel(
            name='QAOfficerDocument',
        ),
        migrations.DeleteModel(
            name='QAOfficerReferral',
        ),
    ]
