# Generated by Django 3.2.13 on 2022-08-16 06:04

from django.db import migrations, models
import django.db.models.deletion
import leaseslicensing.components.competitive_processes.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0066_merge_20220812_1715'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveProcessParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_person', models.IntegerField(blank=True, null=True)),
                ('invited_at', models.DateField(blank=True, null=True)),
                ('removed_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('competitive_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competitive_process_parties', to='leaseslicensing.competitiveprocess')),
                ('party_organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.organisation')),
            ],
            options={
                'ordering': ['invited_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.TextField(blank=True)),
                ('created_by', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('competitive_processes_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_details', to='leaseslicensing.competitiveprocessparty')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartyDetailDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, upload_to=leaseslicensing.components.competitive_processes.models.update_party_detail_doc_filename)),
                ('party_detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='party_detail_documents', to='leaseslicensing.partydetail')),
            ],
        ),
        migrations.AddConstraint(
            model_name='competitiveprocessparty',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('party_organisation__isnull', False), ('party_person', None)), models.Q(('party_organisation', None), ('party_person__isnull', False)), _connector='OR'), name='either_one_null'),
        ),
    ]
