# Generated by Django 3.2.13 on 2022-08-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0067_auto_20220816_1404'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='competitiveprocessparty',
            name='either_one_null',
        ),
        migrations.RenameField(
            model_name='competitiveprocessparty',
            old_name='party_person',
            new_name='party_person_id',
        ),
        migrations.AddConstraint(
            model_name='competitiveprocessparty',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('party_organisation__isnull', False), ('party_person_id', None)), models.Q(('party_organisation', None), ('party_person_id__isnull', False)), _connector='OR'), name='either_one_null'),
        ),
    ]
