# Generated by Django 3.2.13 on 2022-08-17 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0068_auto_20220816_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitiveProcessUserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.IntegerField()),
                ('when', models.DateTimeField(auto_now_add=True)),
                ('what', models.TextField()),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='leaseslicensing.competitiveprocess')),
            ],
            options={
                'ordering': ('-when',),
            },
        ),
        migrations.CreateModel(
            name='CompetitiveProcessLogEntry',
            fields=[
                ('communicationslogentry_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='leaseslicensing.communicationslogentry')),
                ('competitive_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comms_logs', to='leaseslicensing.competitiveprocess')),
            ],
            bases=('leaseslicensing.communicationslogentry',),
        ),
    ]
