# Generated by Django 3.2.13 on 2022-08-18 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0067_auto_20220816_1730'),
        ('leaseslicensing', '0069_competitiveprocesslogentry_competitiveprocessuseraction'),
    ]

    operations = [
    ]
