# Generated by Django 3.2.13 on 2022-08-23 05:01

from django.db import migrations, models
import django.db.models.deletion
import leaseslicensing.components.competitive_processes.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0070_merge_20220818_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveprocess',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='competitiveprocess',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaseslicensing.competitiveprocessparty'),
        ),
        migrations.CreateModel(
            name='CompetitiveProcessDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('uploaded_date', models.DateTimeField(auto_now_add=True)),
                ('_file', models.FileField(max_length=512, upload_to=leaseslicensing.components.competitive_processes.models.update_competitive_process_doc_filename)),
                ('competitive_process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitive_process_documents', to='leaseslicensing.competitiveprocess')),
            ],
        ),
    ]
