# Generated by Django 3.2.13 on 2022-08-18 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0069_proposalrequirement_reminder_date'),
        ('leaseslicensing', '0070_merge_20220818_0917'),
    ]

    operations = [
    ]
