# Generated by Django 3.2.13 on 2022-08-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0071_auto_20220823_1301'),
        ('leaseslicensing', '0071_merge_20220818_1451'),
    ]

    operations = [
    ]
