# Generated by Django 3.2.13 on 2022-08-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0072_merge_20220823_1303'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='competitiveprocessparty',
            name='either_one_null',
        ),
        migrations.RenameField(
            model_name='competitiveprocessparty',
            old_name='party_organisation',
            new_name='organisation',
        ),
        migrations.RenameField(
            model_name='competitiveprocessparty',
            old_name='party_person_id',
            new_name='person_id',
        ),
        migrations.AddConstraint(
            model_name='competitiveprocessparty',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('organisation__isnull', False), ('person_id', None)), models.Q(('organisation', None), ('person_id__isnull', False)), _connector='OR'), name='either_one_null'),
        ),
    ]
