# Generated by Django 3.2.13 on 2022-08-24 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0073_auto_20220823_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveprocessdocument',
            name='input_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
