# Generated by Django 3.2.13 on 2022-08-25 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0074_competitiveprocessdocument_input_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='competitive_process',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_proposal', to='leaseslicensing.competitiveprocess'),
        ),
    ]
