# Generated by Django 3.2.13 on 2022-08-26 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0080_alter_competitiveprocess_generated_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitiveprocess',
            name='generated_proposal',
        ),
        migrations.AddField(
            model_name='proposal',
            name='originating_competitive_process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_proposal', to='leaseslicensing.competitiveprocess'),
        ),
    ]
