# Generated by Django 3.2.13 on 2022-09-02 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0081_auto_20220826_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvaltype',
            name='approval_type_document_types',
        ),
        migrations.CreateModel(
            name='ApprovalTypeDocumentTypeOnApprovalType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory', models.BooleanField(default=False)),
                ('approval_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaseslicensing.approvaltype')),
                ('approval_type_document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaseslicensing.approvaltypedocumenttype')),
            ],
        ),
        migrations.AddField(
            model_name='approvaltype',
            name='approvaltypedocumenttypes',
            field=models.ManyToManyField(through='leaseslicensing.ApprovalTypeDocumentTypeOnApprovalType', to='leaseslicensing.ApprovalTypeDocumentType'),
        ),
    ]
