# Generated by Django 3.2.13 on 2022-09-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0083_alter_approvaltypedocumenttypeonapprovaltype_unique_together'),
        ('leaseslicensing', '0083_rename_created_by_partydetail_created_by_id'),
    ]

    operations = [
    ]
