# Generated by Django 3.2.13 on 2022-09-07 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0083_alter_approvaltypedocumenttypeonapprovaltype_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeasesLicensingSecurityGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('registration_of_interest_approver', 'Registration of Interest Assessor'), ('registration_of_interest_approver', 'Registration of Interest Approver'), ('lease_licence_assessor', 'Lease Licence Assessor'), ('lease_licence_approver', 'Lease Licence Approver'), ('competitive_process_editor', 'Competitive Process Editor'), ('finance', 'Finance')], max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LeasesLicensingSecurityGroupMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailuser', models.IntegerField(null=True)),
                ('active', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='leaseslicensing.leaseslicensingsecuritygroup')),
            ],
        ),
    ]
