# Generated by Django 3.2.13 on 2022-09-06 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0084_merge_20220905_1523'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partydetail',
            old_name='competitive_processes_party',
            new_name='competitive_process_party',
        ),
    ]
