# Generated by Django 3.2.13 on 2022-09-07 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0084_leaseslicensingsecuritygroup_leaseslicensingsecuritygroupmembership'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeasesLicensingSecurityGroup',
            new_name='SecurityGroup',
        ),
        migrations.RenameModel(
            old_name='LeasesLicensingSecurityGroupMembership',
            new_name='SecurityGroupMembership',
        ),
    ]
