# Generated by Django 3.2.13 on 2022-09-07 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0085_auto_20220907_1201'),
        ('leaseslicensing', '0085_rename_competitive_processes_party_partydetail_competitive_process_party'),
    ]

    operations = [
    ]
