# Generated by Django 3.2.13 on 2022-09-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0086_merge_20220907_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiveprocessgeometry',
            name='intersects',
            field=models.BooleanField(default=False),
        ),
    ]
