# Generated by Django 3.2.13 on 2022-09-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0086_merge_20220907_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='assigned_to',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='securitygroup',
            name='name',
            field=models.CharField(choices=[('registration_of_interest_assessor', 'Registration of Interest Assessor'), ('registration_of_interest_approver', 'Registration of Interest Approver'), ('lease_licence_assessor', 'Lease Licence Assessor'), ('lease_licence_approver', 'Lease Licence Approver'), ('competitive_process_editor', 'Competitive Process Editor'), ('finance', 'Finance')], max_length=200),
        ),
    ]
