# Generated by Django 3.2.13 on 2022-09-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0087_auto_20220912_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compliance',
            name='submitter',
            field=models.IntegerField(null=True),
        ),
    ]
