# Generated by Django 3.2.13 on 2022-09-13 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0087_auto_20220913_1055'),
        ('leaseslicensing', '0088_alter_compliance_submitter'),
    ]

    operations = [
    ]
