# Generated by Django 3.2.13 on 2022-09-16 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0089_merge_20220913_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communicationslogentry',
            name='customer',
            field=models.IntegerField(null=True),
        ),
    ]
