# Generated by Django 3.2.13 on 2022-09-20 01:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0090_chargemethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='chargemethod',
            name='key',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chargemethod',
            name='display_name',
            field=models.CharField(max_length=200),
        ),
    ]
