# Generated by Django 3.2.13 on 2022-09-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0091_auto_20220920_0904'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicingDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('base_fee_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('once_off_charge_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('review_once_every', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('invoicing_once_every', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.approval')),
                ('charge_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.chargemethod')),
                ('previous_invoicing_details', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_invoicing_details', to='leaseslicensing.invoicingdetails')),
            ],
        ),
    ]
