# Generated by Django 3.2.13 on 2022-09-27 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0092_invoicingdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDateAnnually',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('date_of_enforcement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDateMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('review_date', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_of_enforcement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDateQuarterly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('review_date_q1', models.DateField()),
                ('review_date_q2', models.DateField()),
                ('review_date_q3', models.DateField()),
                ('review_date_q4', models.DateField()),
                ('date_of_enforcement', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='invoicingdetails',
            name='base_fee_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AlterField(
            model_name='invoicingdetails',
            name='once_off_charge_amount',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=10),
        ),
        migrations.AddField(
            model_name='invoicingdetails',
            name='review_date_annually',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.reviewdateannually'),
        ),
        migrations.AddField(
            model_name='invoicingdetails',
            name='review_date_monthly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.reviewdatemonthly'),
        ),
        migrations.AddField(
            model_name='invoicingdetails',
            name='review_date_quarterly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.reviewdatequarterly'),
        ),
    ]
