# Generated by Django 3.2.13 on 2022-09-27 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0090_alter_communicationslogentry_customer'),
        ('leaseslicensing', '0093_auto_20220927_1303'),
    ]

    operations = [
    ]
