# Generated by Django 3.2.13 on 2022-09-27 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0094_merge_20220927_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicingDateAnnually',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('invoicing_date', models.DateField(blank=True, null=True)),
                ('date_of_enforcement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoicingDateMonthly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('invoicing_date', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date_of_enforcement', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InvoicingDateQuarterly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('invoicing_date_q1', models.DateField()),
                ('invoicing_date_q2', models.DateField()),
                ('invoicing_date_q3', models.DateField()),
                ('invoicing_date_q4', models.DateField()),
                ('date_of_enforcement', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='invoicingdetails',
            name='invoicing_date_annually',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.invoicingdateannually'),
        ),
        migrations.AddField(
            model_name='invoicingdetails',
            name='invoicing_date_monthly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.invoicingdatemonthly'),
        ),
        migrations.AddField(
            model_name='invoicingdetails',
            name='invoicing_date_quarterly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.invoicingdatequarterly'),
        ),
    ]
