# Generated by Django 3.2.13 on 2022-09-28 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0095_auto_20220927_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoicingdetails',
            name='invoicing_date_annually',
        ),
        migrations.RemoveField(
            model_name='invoicingdetails',
            name='invoicing_date_monthly',
        ),
        migrations.RemoveField(
            model_name='invoicingdetails',
            name='invoicing_date_quarterly',
        ),
        migrations.RemoveField(
            model_name='invoicingdetails',
            name='review_date_annually',
        ),
        migrations.RemoveField(
            model_name='invoicingdetails',
            name='review_date_monthly',
        ),
        migrations.RemoveField(
            model_name='invoicingdetails',
            name='review_date_quarterly',
        ),
    ]
