# Generated by Django 3.2.13 on 2022-09-28 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0096_auto_20220928_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumerPriceIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('cpi_value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RepetitionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200, unique=True)),
                ('display_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='invoicingdetails',
            name='invoicing_repetition_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_details_set_for_invoicing', to='leaseslicensing.repetitiontype'),
        ),
        migrations.AddField(
            model_name='invoicingdetails',
            name='review_repetition_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoicing_details_set_for_review', to='leaseslicensing.repetitiontype'),
        ),
    ]
