# Generated by Django 3.2.13 on 2022-09-28 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0097_auto_20220928_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrownLandRentReviewDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('review_date', models.DateField(blank=True, null=True)),
                ('invoicing_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaseslicensing.invoicingdetails')),
            ],
        ),
    ]
