# Generated by Django 3.2.13 on 2022-09-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0098_crownlandrentreviewdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConsumerPriceIndex',
        ),
    ]
