# Generated by Django 3.2.13 on 2022-09-28 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0099_delete_consumerpriceindex'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('name', models.CharField(max_length=200)),
                ('start_date_q1', models.DateField(blank=True, null=True)),
                ('start_date_q2', models.DateField(blank=True, null=True)),
                ('start_date_q3', models.DateField(blank=True, null=True)),
                ('start_date_q4', models.DateField(blank=True, null=True)),
                ('cpi_value_q1', models.FloatField(blank=True, null=True)),
                ('cpi_value_q2', models.DateField(blank=True, null=True)),
                ('cpi_value_q3', models.DateField(blank=True, null=True)),
                ('cpi_value_q4', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
