# Generated by Django 3.2.13 on 2022-09-29 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0100_financialyear'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialYear',
            new_name='ConsumerPriceIndex',
        ),
    ]
