# Generated by Django 3.2.13 on 2022-09-29 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0101_rename_financialyear_consumerpriceindex'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicingdateannually',
            options={'verbose_name_plural': 'Invoicing Date Annually'},
        ),
        migrations.AlterModelOptions(
            name='invoicingdatemonthly',
            options={'verbose_name_plural': 'Invoicing Date Monthly'},
        ),
        migrations.AlterModelOptions(
            name='invoicingdatequarterly',
            options={'verbose_name_plural': 'Invoicing Date Quarterly'},
        ),
        migrations.AlterModelOptions(
            name='reviewdateannually',
            options={'verbose_name_plural': 'Review Date Annually'},
        ),
        migrations.AlterModelOptions(
            name='reviewdatemonthly',
            options={'verbose_name_plural': 'Review Date Monthly'},
        ),
        migrations.AlterModelOptions(
            name='reviewdatequarterly',
            options={'verbose_name_plural': 'Review Date Quarterly'},
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='cpi_value_q1',
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='cpi_value_q2',
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='cpi_value_q3',
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='cpi_value_q4',
        ),
    ]
