# Generated by Django 3.2.13 on 2022-09-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0102_auto_20220929_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumerpriceindex',
            name='cpi_value_q1',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumerpriceindex',
            name='cpi_value_q2',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumerpriceindex',
            name='cpi_value_q3',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consumerpriceindex',
            name='cpi_value_q4',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
