# Generated by Django 3.2.13 on 2022-09-29 08:20

from django.db import migrations, models
import leaseslicensing.components.invoicing.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0103_auto_20220929_1122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='name',
        ),
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='start_date_q1',
            # field=models.DateField(blank=True, default=leaseslicensing.components.invoicing.models.get_start_date_q1, editable=False, null=True),
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='start_date_q2',
            # field=models.DateField(blank=True, default=leaseslicensing.components.invoicing.models.get_start_date_q2, editable=False, null=True),
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='start_date_q3',
            # field=models.DateField(blank=True, default=leaseslicensing.components.invoicing.models.get_start_date_q3, editable=False, null=True),
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='start_date_q4',
            # field=models.DateField(blank=True, default=leaseslicensing.components.invoicing.models.get_start_date_q4, editable=False, null=True),
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
