# Generated by Django 3.2.13 on 2022-09-29 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0104_auto_20220929_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='cpi_value_q1',
            field=models.FloatField(blank=True, null=True, verbose_name='CPI (Q1)'),
        ),
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='cpi_value_q2',
            field=models.FloatField(blank=True, null=True, verbose_name='CPI (Q2)'),
        ),
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='cpi_value_q3',
            field=models.FloatField(blank=True, null=True, verbose_name='CPI (Q3)'),
        ),
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='cpi_value_q4',
            field=models.FloatField(blank=True, null=True, verbose_name='CPI (Q4)'),
        ),
    ]
