# Generated by Django 3.2.13 on 2022-09-29 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0105_auto_20220929_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='start_date_q1',
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='start_date_q2',
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='start_date_q3',
        ),
        migrations.RemoveField(
            model_name='consumerpriceindex',
            name='start_date_q4',
        ),
    ]
