# Generated by Django 3.2.13 on 2022-09-30 01:38

from django.db import migrations, models
import leaseslicensing.components.invoicing.models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0107_consumerpriceindex_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumerpriceindex',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, default=leaseslicensing.components.invoicing.models.get_year, null=True),
        ),
    ]
