# Generated by Django 3.2.13 on 2022-09-30 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0108_alter_consumerpriceindex_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAnnualPercentage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(default=0)),
                ('invoicing_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaseslicensing.invoicingdetails')),
            ],
        ),
        migrations.CreateModel(
            name='FixedAnnualIncrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('increment_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=10)),
                ('invoicing_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaseslicensing.invoicingdetails')),
            ],
        ),
    ]
