# Generated by Django 3.2.13 on 2022-10-04 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0109_fixedannualincrement_fixedannualpercentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PercentageOfGrossTurnover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('percentage', models.FloatField(default=0)),
                ('invoicing_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='leaseslicensing.invoicingdetails')),
            ],
        ),
    ]
