# Generated by Django 3.2.13 on 2022-10-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0110_percentageofgrossturnover'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FixedAnnualIncrement',
            new_name='FixedAnnualIncrementAmount',
        ),
        migrations.RenameModel(
            old_name='FixedAnnualPercentage',
            new_name='FixedAnnualIncrementPercentage',
        ),
    ]
