# Generated by Django 3.2.13 on 2022-10-05 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0111_auto_20221005_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crownlandrentreviewdate',
            name='invoicing_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crown_land_rent_review_dates', to='leaseslicensing.invoicingdetails'),
        ),
        migrations.AlterField(
            model_name='fixedannualincrementamount',
            name='invoicing_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_increment_amounts', to='leaseslicensing.invoicingdetails'),
        ),
        migrations.AlterField(
            model_name='fixedannualincrementpercentage',
            name='invoicing_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annual_increment_percentages', to='leaseslicensing.invoicingdetails'),
        ),
        migrations.AlterField(
            model_name='percentageofgrossturnover',
            name='invoicing_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gross_turnover_percentages', to='leaseslicensing.invoicingdetails'),
        ),
    ]
