# Generated by Django 3.2.13 on 2022-10-06 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0113_proposal_invoicing_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedannualincrementpercentage',
            old_name='percentage',
            new_name='increment_percentage',
        ),
    ]
