# Generated by Django 3.2.13 on 2022-10-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0114_rename_percentage_fixedannualincrementpercentage_increment_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fixedannualincrementamount',
            name='increment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='fixedannualincrementpercentage',
            name='increment_percentage',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='percentageofgrossturnover',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
