# Generated by Django 3.2.13 on 2022-10-11 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0115_auto_20221007_0943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crownlandrentreviewdate',
            options={'ordering': ['review_date']},
        ),
        migrations.AlterModelOptions(
            name='fixedannualincrementamount',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='fixedannualincrementpercentage',
            options={'ordering': ['year']},
        ),
        migrations.AlterModelOptions(
            name='percentageofgrossturnover',
            options={'ordering': ['year']},
        ),
        migrations.AlterField(
            model_name='invoicingdetails',
            name='base_fee_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoicingdetails',
            name='once_off_charge_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
