# Generated by Django 3.2.13 on 2022-10-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0116_auto_20221011_1144'),
        ('leaseslicensing', '0116_auto_20221021_1600'),
    ]

    operations = [
    ]
