# Generated by Django 3.2.13 on 2022-10-26 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0118_auto_20221026_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='deficiency_comment_proposal_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='referrer_comment_proposal_details',
            field=models.TextField(blank=True),
        ),
    ]
