# Generated by Django 3.2.13 on 2022-10-28 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0119_auto_20221026_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='referrer_comment_proposal_details',
        ),
        migrations.AddField(
            model_name='proposal',
            name='assessor_comment_additional_documents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='assessor_comment_deed_poll',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='assessor_comment_map',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='assessor_comment_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='assessor_comment_proposal_impact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='deficiency_comment_additional_documents',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='deficiency_comment_deed_poll',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='deficiency_comment_map',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='deficiency_comment_other',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='deficiency_comment_proposal_impact',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_comment_proposal_details',
            field=models.TextField(blank=True),
        ),
    ]
