# Generated by Django 3.2.16 on 2022-11-04 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0121_auto_20221102_0835'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseLicenceFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('invoice_reference', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('invoice_cover_start_date', models.DateField(blank=True, null=True)),
                ('invoice_cover_end_date', models.DateField(blank=True, null=True)),
                ('date_invoice_sent', models.DateField(blank=True, null=True)),
                ('invoicing_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='leaseslicensing.invoicingdetails')),
            ],
        ),
    ]
