# Generated by Django 3.2.16 on 2022-11-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0121_auto_20221102_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposalrequest',
            name='officer',
            field=models.IntegerField(null=True),
        ),
    ]
