# Generated by Django 3.2.16 on 2022-11-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0122_leaselicencefee'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='proposalassessment',
            constraint=models.UniqueConstraint(fields=('proposal', 'referral'), name='unique_per_proposal_per_assessor_or_referral'),
        ),
    ]
