# Generated by Django 3.2.16 on 2022-11-04 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0123_proposalassessment_unique_per_proposal_per_assessor_or_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaselicencefee',
            name='invoicing_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lease_licence_fees', to='leaseslicensing.invoicingdetails'),
        ),
    ]
