# Generated by Django 3.2.16 on 2022-11-08 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaseslicensing', '0123_auto_20221102_1549'),
        ('leaseslicensing', '0124_alter_leaselicencefee_invoicing_details'),
    ]

    operations = [
    ]
