from django.db import models


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    modified_at = models.DateTimeField(auto_now=True, null=True)

    class Meta:
        abstract = True


class ChargeMethod(models.Model):
    """A class to represent a competitive process"""

    key = models.CharField(max_length=200, unique=True)
    display_name = models.CharField(max_length=200,)

    class Meta:
        app_label = "leaseslicensing"

    def __str__(self):
        return self.display_name


class InvoicingDetails(BaseModel):
    """
    This is the main model to store invoicing details, generated by a proposal first (Proposal has a field: invoicing_details)
    then copied and/or edited as business run
    """
    charge_method = models.ForeignKey(ChargeMethod, null=True, blank=True, on_delete=models.SET_NULL)
    base_fee_amount = models.DecimalField(max_digits=10, decimal_places=2)
    once_off_charge_amount = models.DecimalField(max_digits=10, decimal_places=2)
    review_once_every = models.PositiveSmallIntegerField(null=True, blank=True)
    invoicing_once_every = models.PositiveSmallIntegerField(null=True, blank=True)

    approval = models.ForeignKey('Approval', null=True, blank=True, on_delete=models.SET_NULL)
    previous_invoicing_details = models.OneToOneField('self', null=True, blank=True, related_name='next_invoicing_details', on_delete=models.SET_NULL)

    class Meta:
        app_label = "leaseslicensing"
